repos:
  - repo: https://github.com/dycw/pre-commit-hooks
    rev: 0.0.48
    hooks:
      - id: markdown
      - id: no-binary
      - id: no-commit
      - id: prettier
      - id: python
      - id: text
      - id: universal
